### ISSUE TITLE
Rainbow colors

### ISSUE THREAD

**Issue by ivanpierre** [tonsky/clojure-warrior#1]
Hello Tonsky,
I know the plug-in is fresh. But some remarks.
The choice of degrading colours regularly is nice in the demo, but don't catch the goal.
The typical errors are 1 or 2 levels discrepancies, so it's better to have tougher colour differences for closer level relations.
But 'I'm sure you'll put CSS attributes in the config, level 1 is bad in dark theme. ;)
Nice resolution for the string and remarks of the other extension.
Good job.

**Comment by tonsky** [comment]
Thanks! Yeah, I realise that. There’ll be settings for that

**Comment by tonsky** [comment]
Fixed in 0.1.4, thanks for the idea!
