### ISSUE TITLE
Disabled rainbow brackets also turn off other features

### ISSUE THREAD

**Issue by CheatEx** [tonsky/clojure-warrior#12]
When I disable rainbow as [suggested by Calva](https://marketplace.visualstudio.com/items?itemName=betterthantomorrow.calva)
`"clojureWarrior.bracketColors": []`
unbalanced and cursor-matching highlights are also disabled.

There is a workaround to add a single color
`"clojureWarrior.bracketColors": ["#DDD"]`
but it has to be matched manually to the current color theme.

**Comment by PEZ** [comment]
Maybe it would make sense to have an explicit option for disabling rainbow brackets. (That didn't also disable the matching highlight, of course. :smile: )

**Comment by tonsky** [comment]
That suggestion just probably breaks clojure warrior. I’m happy to accept a plugin that adds a workaround. Maybe `"clojureWarrior.colorBrackets": false`?

**Comment by PEZ** [comment]
>  I’m happy to accept a plugin that adds a workaround.

Not sure what this means.

> Maybe `"clojureWarrior.colorBrackets": false`?

I think that is the best option.

Some context: Calva bundles Clojure Warrior and at the same time disables vscode's built-in bracket matching (which is stupid and wrong) and enables Clojure Warrior's bracket matching instead. But, apparently, som users don't want the rainbow brackets that is (from my understanding) the main feature of Clojure Warrior.

**Comment by tonsky** [comment]
> I’m happy to accept a plugin that adds a workaround.

plugin -> Pull Request 🤦‍♂️

**Comment by tonsky** [comment]
> at the same time disables vscode's built-in bracket matching (which is stupid and wrong)

Well if you don’t disable it you will have two highlighers sending mixed signals to user. I disable built-in matching as well.

The problem is that VS Code matching will stop working in all other file types that are not Clojure. I have found no decent solution for that.

**Comment by PEZ** [comment]
Calva scopes the setting to Clojure files. I'm pretty sure that works.

**Comment by tonsky** [comment]
> Calva scopes the setting to Clojure files. I'm pretty sure that works.

Thanks! Seems to work, copied it to Clojure Warrior too.

I just fixed the issue (setting `bracketColors` to `[]` does not break Clojure Warrior anymore). I also added `clojureWarrior.enableBracketColors` so you can enable/disable rainbow brackets with a single more semantic property.

Check out 0.2.0 and let me know it anything breaks.

**Comment by CheatEx** [comment]
After update the new option appears and works as expected. Thanks everyone.

**Comment by PEZ** [comment]
Thanks, @tonsky! I'll remove that setting from Calva, now that it ”lives” in its proper place.
