### ISSUE TITLE
Version 0.2.0 conflicts with Calva formatting for some

### ISSUE THREAD

**Issue by PEZ** [tonsky/clojure-warrior#13]
Hello,

In BetterThanTomorrow/calva/issues/243 two people report that Calva formatting has stopped working and that they get it to work again by downgrading to Clojure Warrior 0.1.8.

I think this probably is a Calva issue, but I have been staring at the code now for a while and think maybe if we looked at it together we could pinpoint the root of the problem.

I can't reproduce the error, which makes it extra hard to debug.

**Comment by tonsky** [comment]
I can reproduce it. No exceptions in console, nothing. Does Calva interacts with Clojure Warrior in any way? Or is it just another plugin working along Calva?

**Comment by PEZ** [comment]
Great that you can repro! There is no interaction.  They just go side by side.

**Comment by PEZ** [comment]
How about a Chrome Remote Desktop session, or something like that?

**Comment by tonsky** [comment]
Ping me on Telegram @nikitonsky
