### ISSUE TITLE
Tricky comment cases

### ISSUE THREAD

**Issue by tonsky** [tonsky/clojure-warrior#15]
Here's a few cases that don't work correctly yet.

<img width="176" alt="Screenshot 2019-07-10 at 16 14 41" src="https://user-images.githubusercontent.com/4028554/60976509-17862080-a32e-11e9-9c3c-5b9446f4f392.png">

<img width="244" alt="Screenshot 2019-07-10 at 16 16 08" src="https://user-images.githubusercontent.com/4028554/60976518-1c4ad480-a32e-11e9-842c-f5c92a8db2ab.png">

Well, it looks like it might all be the same case actually ;)

_Originally posted by @svdo in https://github.com/tonsky/clojure-warrior/pull/14#issuecomment-510080267_

**Comment by tonsky** [comment]
we need a real parser :)

**Comment by maxp** [comment]
Another issue with comments

```
;<TRAILING SPACE>
(fn [] (fn []))
```

**Comment by tonsky** [comment]
Try 0.2.4
