### ISSUE TITLE
Experiencing interesting comment issues

### ISSUE THREAD

**Issue by cjbarre** [tonsky/clojure-warrior#17]
![image](https://user-images.githubusercontent.com/7362038/61063769-5f03bf80-a3b5-11e9-8898-f49a2bf9109b.png)

Hi Nikita, thanks for your hard work 😃 

I'm not entirely sure the first instance is because of clojure-warrior, but I just noticed it was happening today - could be related to my theme.

The other two, however, I just noticed today. It seems that once I have a ;; style comment, the rest of the file's bracket coloring is thrown off.

Any idea if this might just be a problem on my end?

**Comment by tonsky** [comment]
Thanks! I can reproduce all of these (;; line needs a trailing comment). We fucked up :)

**Comment by tonsky** [comment]
@PEZ please take a look :)

**Comment by tonsky** [comment]
Try 0.2.4

**Comment by cjbarre** [comment]
Oh hey, thanks, I had second thoughts and accidentally hit the closed button and decided to leave it 😄 

Appreciated!
